spring.application.name=configuration-validation-service

server.port=8080

# =====================================================
# LOG LEVELS
# =====================================================
logging.level.root=INFO

#logging.level.com.frauscher=DEBUG

# =====================================================
# LOG FILE CONFIGURATION
# =====================================================
logging.file.name=logs/configuration-validation-service.log

# =====================================================
# LOG FORMAT
# =====================================================
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.console=%d{HH:mm:ss} %-5level %msg%n

# =====================================================
# LOG ROTATION
# =====================================================
logging.logback.rollingpolicy.file-name-pattern=logs/configuration-validation-service-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=14
logging.logback.rollingpolicy.total-size-cap=200MB

# =====================================================
# ACTUATOR CONFIGURATION
# =====================================================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.info.enabled=true
management.endpoint.metrics.enabled=true

# =====================================================
# CORS CONFIGURATION
# =====================================================
spring.web.cors.allowed-origins=http://at-cvt01.frauscher.host:6443
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true



