# Communication Failure Mappings
COMM_FAIL.0=0 - normal
COMM_FAIL.1=1 - fault

# Behavior General Mappings
BEHAV_GE.0=0 - Restriction at fault, no restriction at power-up  
BEHAV_GE.1=1 - No reset restriction
BEHAV_GE.2=2 - Reset restriction


# Clear Track Mappings
CLR_TRACK.0=0 - Clearing of track with at least 2 counting heads
CLR_TRACK.1=1 - Clearing of track with at 1 counting heads
CLR_TRACK.2=2 - Clearing of track at all counting heads
CLR_TRACK.3=3 - Clearing of track at first 2 counting heads

# Reset In Mappings
RESET_IN.0=0 - not allowed
RESET_IN.1=1 - reset
RESET_IN.2=2 - (reset + clearing of track)
RESET_IN.3=3 - pre-reset
RESET_IN.4=4 - (pre-reset + clearing of track)
RESET_IN.5=5 - (pre-reset + reset)
RESET_IN.6=6 - (pre-reset + reset + clearing of track)
RESET_IN.7=7 - reset or pre-reset
RESET_IN.8=8 - reset or (pre-reset + clearing of track)
RESET_IN.9=9 - not allowed
RESET_IN.10=10 - Reset or (pre-reset + reset + clearing of track)
RESET_IN.11=11 - (reset + clearing of track) or pre-reset
RESET_IN.12=12 - (reset + clearing of track) or (pre-reset + clearing of track)
RESET_IN.13=13 - (reset + clearing of track) or (pre-reset + reset)

# Reset Out Mappings
RESET_OUT.0=0 - not allowed
RESET_OUT.1=1 - reset
RESET_OUT.2=2 - (reset + clearing of track)
RESET_OUT.3=3 - pre-reset
RESET_OUT.4=4 - (pre-reset + clearing of track)
RESET_OUT.5=5 - (pre-reset + reset)
RESET_OUT.6=6 - (pre-reset + reset + clearing of track)
RESET_OUT.7=7 - reset or pre-reset
RESET_OUT.8=8 - reset or (pre-reset + clearing of track)
RESET_OUT.9=9 - not allowed
RESET_OUT.10=10 - Reset or (pre-reset + reset + clearing of track)
RESET_OUT.11=11 - (reset + clearing of track) or pre-reset
RESET_OUT.12=12 - (reset + clearing of track) or (pre-reset + clearing of track)
RESET_OUT.13=13 - (reset + clearing of track) or (pre-reset + reset)

# Behavior Reset Mappings
BEHAV_RESET.0=0 - Direct Reset
BEHAV_RESET.1=1 - Restricted Reset
BEHAV_RESET.2=2 - Preparatory Direct Reset
BEHAV_RESET.3=3 - Preparatory Restricted Reset
BEHAV_RESET.4=4 - Auxiliary Reset
BEHAV_RESET.5=5 - Pre-Reset
BEHAV_RESET.6=6 - Reset
BEHAV_RESET.7=7 - Disabled

# Behavior Simul Mappings
BEHAV_SIMUL.0=0 - Default
BEHAV_SIMUL.1=1 - Disabled

# Interval Mappings
INTERVAL.0=0 (10 ms)
INTERVAL.1=1 (40 ms)
INTERVAL.2=2 (80 ms)
INTERVAL.3=3 (160 ms)

#logic type
LOGIC_TYPE.0=(OR)
LOGIC_TYPE.1=(AND)

#Reset Type
RESET_TYPE.0=0 - direct
RESET_TYPE.1=1 - restricted
RESET_TYPE.2=2 - preparatory
RESET_TYPE.3=3 - preparatory restricted reset

#IOEXB
BEHAV_INPUT1.0 = 0 - Direct reset
BEHAV_INPUT1.1 = 1 - Restricted reset
BEHAV_INPUT1.2 = 2 - Preparatory direct reset
BEHAV_INPUT1.3 = 3 - Preparatory restricted reset
BEHAV_INPUT1.4 = 4 - Auxiliary reset
BEHAV_INPUT1.5 = 5 - Pre-Reset
BEHAV_INPUT1.6 = 6 - Reset
BEHAV_INPUT1.7 = 7 - not allowed

BEHAV_INPUT2.0 = 0 - Direct reset
BEHAV_INPUT2.1 = 1 - Restricted reset
BEHAV_INPUT2.2 = 2 - Preparatory direct reset
BEHAV_INPUT2.3 = 3 - Preparatory restricted reset
BEHAV_INPUT2.4 = 4 - Auxiliary reset
BEHAV_INPUT2.5 = 5 - Pre-Reset
BEHAV_INPUT2.6 = 6 - Reset
BEHAV_INPUT2.7 = 7 - not allowed

BEHAV_INPUT3.0 = 0 - Direct reset
BEHAV_INPUT3.1 = 1 - Restricted reset
BEHAV_INPUT3.2 = 2 - Preparatory direct reset
BEHAV_INPUT3.3 = 3 - Preparatory restricted reset
BEHAV_INPUT3.4 = 4 - Auxiliary reset
BEHAV_INPUT3.5 = 5 - Pre-Reset
BEHAV_INPUT3.6 = 6 - Reset
BEHAV_INPUT3.7 = 7 - not allowed

BEHAV_IOEXB.0=0 - Direct Reset
BEHAV_IOEXB.1=1 - Restricted Reset
BEHAV_IOEXB.2=2 - Preparatory Direct Reset
BEHAV_IOEXB.3=3 - Preparatory Restricted Reset
BEHAV_IOEXB.4=4 - Auxiliary Reset
BEHAV_IOEXB.5=5 - Pre-Reset
BEHAV_IOEXB.6=6 - Reset
BEHAV_IOEXB.7=7 - Disabled

TYPE_IN1.0 = 0 - standard
TYPE_IN1.1 = 1 - extended

TYPE_IN2.0 = 0 - standard
TYPE_IN2.1 = 1 - extended

TYPE_IN3.0 = 0 - standard
TYPE_IN3.1 = 1 - extended

TYPE_IOEXB.0 = 0 - standard
TYPE_IOEXB.1 = 1 - extended

#cooperative reset IOEXB CTRL_TYPE
CTRL_TYPE.0 = 0 - pulse triggered
CTRL_TYPE.1 = 1 - status triggered

#ioexb axle counting output
CLR_OCC.0 = 0 - failsafe clear indication
CLR_OCC.1 =  1 occupied indication

TYPE_AUX1.0 = 0 - Standard auxiliary output1
TYPE_AUX1.1 = 1 Extended auxiliary output1

TYPE_AUX2.0 = 0 - Standard auxiliary output2
TYPE_AUX2.1 = 1 - Extended auxiliary output2

AUX1_OUT.0 = 0 - reset restriction
AUX1_OUT.1 = 1 - reset ability
AUX1_OUT.2 = 2 - error/com. error
AUX1_OUT.3 = 3 - clr of track/partial trav. error
AUX1_OUT.4 = 4 - occ status or fault
AUX1_OUT.5 = 5 - reset accepted
AUX1_OUT.6 = 6 - reset rejected
AUX1_OUT.7 = 7 - clearing of track

AUX2_OUT.0 = 0 - reset restriction
AUX2_OUT.1 = 1 - reset ability
AUX2_OUT.2 = 2 - error/com. error
AUX2_OUT.3 = 3 - clr of track/partial trav. error
AUX2_OUT.4 = 4 - occ status or fault
AUX2_OUT.5 = 5 - reset accepted
AUX2_OUT.6 = 6 - reset rejected
AUX2_OUT.7 = 7 - clearing of track

AUX1_NO_NC.0 = 0 - open
AUX1_NO_NC.1 = 1 - closed

AUX2_NO_NC.0 = 0 - open
AUX2_NO_NC.1 = 1 - closed

#IOEXB data transmission

SAFETY_LEVEL_IN.0 = 0 - NOT USED
SAFETY_LEVEL_IN.1 = 1 - SINGLE
SAFETY_LEVEL_IN.2 = 2 - DUAL
SAFETY_LEVEL_IN.3 = 3 - QUAD

SAFETY_LEVEL_OUT.0 = 0 - NOT USED
SAFETY_LEVEL_OUT.1 = 1 - SINGLE
SAFETY_LEVEL_OUT.2 = 2 - DUAL
SAFETY_LEVEL_OUT.3 = 3 - QUAD

SAFE_OUT_FDBCK_QUAD.0 = 0 - disabled
SAFE_OUT_FDBCK_QUAD.1 = 1 - enabled

#COMM
MY_MASK_NW1.24 = 255.255.255.0
MY_MASK_NW2.24 = 255.255.255.0
