package com.frauscher.ConfigurationValidationService.model;

import java.util.List;

/**
 * A detail-table row that can carry v2 per-cell mismatch annotations. Implemented by the eight detail
 * DTOs; the getter/setter are generated by Lombok. Lets the {@code MismatchAnnotator} append a
 * {@link MismatchAnnotation} to any row uniformly.
 */
public interface Annotatable {

    List<MismatchAnnotation> getMismatches();

    void setMismatches(List<MismatchAnnotation> mismatches);
}
